-- CNPJ - TELEFONES
SELECT 'TELEFONE' AS CONSULTA,
                CONCAT(A.NUM_DDD1, A.NUM_TELEFONE1) AS TELEFONE,
                A.NUM_CNPJ,
                A.NOME

FROM DGI_CONSULTA.IMPORTADO.CNPJ A
WHERE A.NUM_CNPJ IN (SELECT CNPJ FROM #CNPJ) AND NOT A.NUM_TELEFONE1 IS NULL

UNION

SELECT
	'TELEFONE' AS CONSULTA,
	CONCAT(A.NUM_DDD2, A.NUM_TELEFONE2) AS TELEFONE,
	A.NUM_CNPJ,
	A.NOME
FROM
	DGI_CONSULTA.IMPORTADO.CNPJ A
WHERE
	A.NUM_CNPJ IN (SELECT CNPJ FROM #CNPJ) AND
	NOT A.NUM_TELEFONE2 IS NULL

UNION

SELECT
	'TELEFONE' AS CONSULTA,
	CONCAT(A.NUM_DDD_FAX, A.NUM_FAX) AS TELEFONE,
	A.NUM_CNPJ,
	A.NOME

FROM
	DGI_CONSULTA.IMPORTADO.CNPJ A
WHERE
	A.NUM_CNPJ IN (SELECT CNPJ FROM #CNPJ) AND NOT A.NUM_FAX IS NULL

ORDER BY
	TELEFONE,
	A.NUM_CNPJ
