;WITH
	QRY_SOCIO AS (
		SELECT
				'SOCIO' AS CONSULTA,
				A.NUM_CNPJ_EMPRESA,
				B.NOME AS NOME_EMPRESA,
				A.NUM_CPF AS CPF_SOCIO,
				A.NOME AS NOME_SOCIO,
				C.DESCR AS QUALIFICACAO_SOCIO,
				A.DATA_ENTRADA_SOCIEDADE,
				A.DATA_DE_EXCLUSAO_NA_SOCIEDADE,
				A.VALOR_PERCENTUA_CAPITAL_SOCIAL
		FROM
			importado.SOCIO A 
			INNER JOIN importado.CNPJ B
				ON A.NUM_CNPJ_EMPRESA = B.NUM_CNPJ 
			INNER JOIN importado.QUALIFICACAO_SOCIO_RESP_REPRES C
				ON A.COD_QUALIFICACAO_SOCIO = C.COD
		WHERE
			A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ))

-- CRIAÇÃO DE TABELAS TEMPORÁRIAS

SELECT * 
INTO #TEMP_SOCIO
FROM QRY_SOCIO

SELECT DISTINCT *
INTO #TEMP_CPF_SOCIO
FROM (SELECT CPF_SOCIO AS CPF FROM #TEMP_SOCIO) AS TEMP_CPF_SOCIO
