-- CNPJ - SOCIO(S), REPRESENTANTE(S) E PARTICIPACOES SOCIETARIAS

SELECT
	'SOCIO' AS CONSULTA,
	A.NUM_CNPJ_EMPRESA,
	A.NOME AS NOME_SOCIO,
	A.NUM_CPF,
	B.NOME AS NOME_EMPRESA,
	C.DESCR AS QUALIFICACAO_SOCIO,
	A.DATA_ENTRADA_SOCIEDADE,
	A.DATA_DE_EXCLUSAO_NA_SOCIEDADE,
	A.VALOR_PERCENTUA_CAPITAL_SOCIAL

FROM
  DGI_CONSULTA.IMPORTADO.SOCIO A 
  INNER JOIN DGI_CONSULTA.IMPORTADO.CNPJ B
    ON A.NUM_CNPJ_EMPRESA = B.NUM_CNPJ 
  INNER JOIN DGI_CONSULTA.IMPORTADO.QUALIFICACAO_SOCIO_RESP_REPRES C
    ON A.COD_QUALIFICACAO_SOCIO = C.COD

WHERE
	A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ)

ORDER BY
	A.NUM_CPF,
	A.NOME
