SELECT
		'PJ' AS CONSULTA,
		A.NUM_CNPJ,
		A.NOME,
		CASE
			WHEN A.IND_MATRIZ_FILIAL = 1 THEN 'Matriz' ELSE 'Filial'
		END AS IND_MATRIZ_FILIAL,
		A.DATA_ABERTURA_ESTABELECIMENTO, 
		A.situacao_descricao SITUACAO_CADASTRAL,
		A.DATA_SITUACAO_CADASTRAL,
		C.DESCR AS ATIVIDADE_ECONOMICA,
		D.DESCR AS NATUREZA_JURIDICA,
		E.DESCR AS PORTE_EMPRESA,
		A.DESCR_EMAIL,
		A.TIPO_LOGRADOURO,
		A.DESCR_LOGRADOURO,
		A.NUM_LOGRADOURO,
		A.DESCR_COMPLEMENTO_LOGRADOURO,
		A.NOME_BAIRRO,
		A.NUM_CEP,
		A.NOME_MUNICIPIO,
		A.SIGLA_UF,
		A.NUM_DDD1,
		A.NUM_TELEFONE1,
		A.NUM_DDD2,
		A.NUM_TELEFONE2,
		A.NUM_DDD_FAX,
		A.NUM_FAX,
		A.VALOR_CAPITAL_SOCIAL
FROM
	DGI_CONSULTA.IMPORTADO.CNPJ A 
	INNER JOIN IMPORTADO.ATIVIDADE_ECONOMICA C
				ON A.COD_ATIVIDADE_ECON_PRINCIPAL = C.COD
	INNER JOIN IMPORTADO.NATUREZA_JURIDICA D
				ON A.COD_NATUREZA_JURIDICA = D.COD
	INNER JOIN IMPORTADO.PORTE_EMPRESA E
        ON A.COD_PORTE_EMPRESA = E.COD
WHERE
	A.NUM_CNPJ IN (SELECT CNPJ FROM #CNPJ)
ORDER BY
	A.NUM_CNPJ,
	A.IND_MATRIZ_FILIAL,
	DATA_ABERTURA_ESTABELECIMENTO