SELECT DISTINCT
	'PARENTESCO' AS CONSULTA,
	A.CPF1,
	B.NOME AS NOME1,
	A.RELACAO,
	D.NOME AS NOME2,
	A.CPF2

FROM
	DGI_CONSULTA.IMPORTADO.RELACAO_PF_PF A
	LEFT JOIN DGI_CONSULTA.IMPORTADO.CPF B
		ON A.CPF1 = B.NUM_CPF
	LEFT JOIN DGI_CONSULTA.IMPORTADO.RELACAO_PF_PF C
		ON A.CPF1 = C.CPF1
	INNER JOIN DGI_CONSULTA.IMPORTADO.CPF D
		ON A.CPF2 = D.NUM_CPF

WHERE
	A.CPF1 IN (	SELECT
					A.NUM_CPF
				FROM
					DGI_CONSULTA.IMPORTADO.SOCIO A
                WHERE
					A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ))

UNION

SELECT DISTINCT
	'PARENTESCO' AS CONSULTA,
	A.CPF1,
	B.NOME AS NOME1,
	A.RELACAO,
	D.NOME AS NOME2,
	A.CPF2

FROM
	DGI_CONSULTA.IMPORTADO.RELACAO_PF_PF A
	LEFT JOIN DGI_CONSULTA.IMPORTADO.CPF B
		ON A.CPF1 = B.NUM_CPF
	LEFT JOIN DGI_CONSULTA.IMPORTADO.RELACAO_PF_PF C
		ON A.CPF1 = C.CPF1
	INNER JOIN DGI_CONSULTA.IMPORTADO.CPF D
		ON A.CPF2 = D.NUM_CPF

WHERE
	A.CPF2 IN (	SELECT
					A.NUM_CPF
				FROM
					DGI_CONSULTA.IMPORTADO.SOCIO A
                WHERE
					A.NUM_CNPJ_EMPRESA
				IN (SELECT CNPJ FROM #CNPJ))

UNION

SELECT DISTINCT
	'PARENTESCO' AS CONSULTA,
	A.CPF1,
	B.NOME AS NOME1,
	A.RELACAO,
	D.NOME AS NOME2,
	A.CPF2

FROM
	DGI_CONSULTA.IMPORTADO.PARENTESCO_RELACAO_PF_PF A
	LEFT JOIN DGI_CONSULTA.IMPORTADO.CPF B
		ON A.CPF1 = B.NUM_CPF
	LEFT JOIN DGI_CONSULTA.IMPORTADO.PARENTESCO_RELACAO_PF_PF C
		ON A.CPF1 = C.CPF1
	INNER JOIN DGI_CONSULTA.IMPORTADO.CPF D
		ON A.CPF2 = D.NUM_CPF

WHERE
	A.CPF1 IN (	SELECT
					A.NUM_CPF
				FROM
					DGI_CONSULTA.IMPORTADO.SOCIO A
                WHERE
					A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ))

UNION

SELECT DISTINCT
	'PARENTESCO' AS CONSULTA,
	A.CPF1,
	B.NOME AS NOME1,
	A.RELACAO,
	D.NOME AS NOME2,
	A.CPF2

FROM
	DGI_CONSULTA.IMPORTADO.PARENTESCO_RELACAO_PF_PF A
		LEFT JOIN DGI_CONSULTA.IMPORTADO.CPF B
			ON A.CPF1 = B.NUM_CPF
		LEFT JOIN DGI_CONSULTA.IMPORTADO.PARENTESCO_RELACAO_PF_PF C
			ON A.CPF1 = C.CPF1
		INNER JOIN DGI_CONSULTA.IMPORTADO.CPF D
			ON A.CPF2 = D.NUM_CPF

WHERE
	A.CPF2 IN (	SELECT
					A.NUM_CPF
				FROM
					DGI_CONSULTA.IMPORTADO.SOCIO A
                WHERE
					A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ))

ORDER BY
	A.CPF1,
	A.CPF2
