-- !preview conn=DBI::dbConnect(RSQLite::SQLite())

SELECT DISTINCT 'CAGED CONTAGEM' AS CONSULTA,
                A.NUM_CNPJ,
                A.NOME,
                B.ANO_DECLARADO,
                COUNT(B.CPF) AS QTDE
FROM DGI_CONSULTA.IMPORTADO.CNPJ A INNER JOIN DGI_CONSULTA.IMPORTADO.CAGED B
                ON A.NUM_CNPJ = B.CNPJ

WHERE A.NUM_CNPJ IN (SELECT CNPJ FROM #CNPJ)

GROUP BY A.NUM_CNPJ,
    A.NOME,
    B.ANO_DECLARADO

ORDER BY A.NUM_CNPJ,
                B.ANO_DECLARADO
