WITH
	CONSULTA_SOCIO_PARENTE_RELACAO_PFPF AS
		(SELECT DISTINCT
			A.CPF1,
			B.NOME AS NOME_CPF1,
			C.NUM_CNPJ_EMPRESA AS NUM_CNPJ_EMPRESA1,
			E.DESCR AS QUALIFICACAO1,
			D.NOME AS NOME_EMPRESA1,
			C.DATA_ENTRADA_SOCIEDADE AS DATA_ENTRADA_SOCIEDADE1,
			C.DATA_DE_EXCLUSAO_NA_SOCIEDADE AS DATA_EXCLUSAO_SOCIEDADE1,
			A.RELACAO,
			A.CPF2
		FROM
			DGI_CONSULTA.IMPORTADO.RELACAO_PF_PF A
			INNER JOIN DGI_CONSULTA.IMPORTADO.CPF B
				ON A.CPF1 = B.NUM_CPF
			INNER JOIN DGI_CONSULTA.IMPORTADO.SOCIO C
				ON A.CPF1 = C.NUM_CPF
			INNER JOIN DGI_CONSULTA.IMPORTADO.CNPJ D
				ON C.NUM_CNPJ_EMPRESA = D.NUM_CNPJ 
			INNER JOIN DGI_CONSULTA.IMPORTADO.QUALIFICACAO_SOCIO_RESP_REPRES E
				ON C.COD_QUALIFICACAO_SOCIO = E.COD
		WHERE
			CPF1 IN (SELECT
						A.NUM_CPF
					FROM
						DGI_CONSULTA.IMPORTADO.SOCIO A
					WHERE
						A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ))
		UNION

		SELECT DISTINCT
			A.CPF1,
			B.NOME AS NOME_CPF1,
			C.NUM_CNPJ_EMPRESA AS NUM_CNPJ_EMPRESA1,
			E.DESCR AS QUALIFICACAO1,
			D.NOME AS NOME_EMPRESA1,
			C.DATA_ENTRADA_SOCIEDADE AS DATA_ENTRADA_SOCIEDADE1,
			C.DATA_DE_EXCLUSAO_NA_SOCIEDADE AS DATA_EXCLUSAO_SOCIEDADE1,
			A.RELACAO,
			A.CPF2

		FROM
			DGI_CONSULTA.IMPORTADO.PARENTESCO_RELACAO_PF_PF A
			INNER JOIN DGI_CONSULTA.IMPORTADO.CPF B
				ON A.CPF1 = B.NUM_CPF
			INNER JOIN DGI_CONSULTA.IMPORTADO.SOCIO C
				ON A.CPF1 = C.NUM_CPF
			INNER JOIN DGI_CONSULTA.IMPORTADO.CNPJ D
				ON C.NUM_CNPJ_EMPRESA = D.NUM_CNPJ
			INNER JOIN DGI_CONSULTA.IMPORTADO.QUALIFICACAO_SOCIO_RESP_REPRES E
				ON C.COD_QUALIFICACAO_SOCIO = E.COD
		WHERE
			CPF1 IN (SELECT
						A.NUM_CPF
					FROM
						DGI_CONSULTA.IMPORTADO.SOCIO A
					WHERE
						A.NUM_CNPJ_EMPRESA
						IN (SELECT
								CNPJ
							FROM #CNPJ))),


	CONSULTA_SOCIO_PARENTE_PARENTESCO_RELACAO_PFPF AS
		(SELECT DISTINCT
			A.CPF1,
			RELACAO,
			A.CPF2,
			B.NOME AS NOME_CPF2,
			D.DESCR AS QUALIFICACAO2,
			E.NUM_CNPJ AS NUM_CNPJ_EMPRESA2,
			E.NOME AS NOME_EMPRESA2,
			C.DATA_ENTRADA_SOCIEDADE AS DATA_ENTRADA_SOCIEDADE2,
			C.DATA_DE_EXCLUSAO_NA_SOCIEDADE AS DATA_EXCLUSAO_SOCIEDADE2
		FROM
			DGI_CONSULTA.IMPORTADO.RELACAO_PF_PF A
			INNER JOIN DGI_CONSULTA.IMPORTADO.CPF B
				ON A.CPF2 = B.NUM_CPF
			INNER JOIN DGI_CONSULTA.IMPORTADO.SOCIO C
				ON A.CPF2 = C.NUM_CPF
			INNER JOIN DGI_CONSULTA.IMPORTADO.QUALIFICACAO_SOCIO_RESP_REPRES D
				ON C.COD_QUALIFICACAO_SOCIO = D.COD
			LEFT JOIN DGI_CONSULTA.IMPORTADO.CNPJ E
				ON C.NUM_CNPJ_EMPRESA = E.NUM_CNPJ
		WHERE
			CPF2 IN (SELECT
						A.NUM_CPF
					FROM
						DGI_CONSULTA.IMPORTADO.SOCIO A
					WHERE
						A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ))

		UNION
		
		SELECT DISTINCT
			A.CPF1,
			RELACAO,
			A.CPF2,
			B.NOME AS NOME_CPF2,
			D.DESCR AS QUALIFICACAO2,
			E.NUM_CNPJ AS NUM_CNPJ_EMPRESA2,
			E.NOME AS NOME_EMPRESA2,
			C.DATA_ENTRADA_SOCIEDADE AS DATA_ENTRADA_SOCIEDADE2,
			C.DATA_DE_EXCLUSAO_NA_SOCIEDADE AS DATA_EXCLUSAO_SOCIEDADE2

		FROM 
			DGI_CONSULTA.IMPORTADO.PARENTESCO_RELACAO_PF_PF A 
			INNER JOIN DGI_CONSULTA.IMPORTADO.CPF B
				ON A.CPF2 = B.NUM_CPF 
			INNER JOIN DGI_CONSULTA.IMPORTADO.SOCIO C
				ON A.CPF2 = C.NUM_CPF 
			INNER JOIN DGI_CONSULTA.IMPORTADO.QUALIFICACAO_SOCIO_RESP_REPRES D
				ON C.COD_QUALIFICACAO_SOCIO = D.COD 
			LEFT JOIN DGI_CONSULTA.IMPORTADO.CNPJ E
				ON C.NUM_CNPJ_EMPRESA = E.NUM_CNPJ
		WHERE
			CPF2 IN (SELECT
						A.NUM_CPF
					FROM 
						DGI_CONSULTA.IMPORTADO.SOCIO A
					WHERE 
						A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ)))


-- QUERY PRINCIPAL

SELECT DISTINCT
	'SOCIO-PARENTESCO' AS CONSULTA,
	PR.CPF1,
	PR.NOME_CPF1,
	PR.QUALIFICACAO1,
	PR.NUM_CNPJ_EMPRESA1,
	PR.NOME_EMPRESA1,
	PR.DATA_ENTRADA_SOCIEDADE1,
	PR.DATA_EXCLUSAO_SOCIEDADE1,
	PR.CPF2,
	PR.RELACAO,
	PA.NOME_CPF2,
	PA.QUALIFICACAO2,
	PA.NUM_CNPJ_EMPRESA2,
	PA.NOME_EMPRESA2,
	PA.DATA_ENTRADA_SOCIEDADE2,
	PA.DATA_EXCLUSAO_SOCIEDADE2
FROM
	CONSULTA_SOCIO_PARENTE_RELACAO_PFPF PR
	INNER JOIN CONSULTA_SOCIO_PARENTE_PARENTESCO_RELACAO_PFPF PA
		ON PR.CPF1 = PA.CPF1 AND PR.CPF2 = PA.CPF2

WHERE
	PR.NUM_CNPJ_EMPRESA1 <> PA.NUM_CNPJ_EMPRESA2
	AND PR.NUM_CNPJ_EMPRESA1 IN (SELECT CNPJ FROM #CNPJ) 
	AND PA.NUM_CNPJ_EMPRESA2 IN (SELECT CNPJ FROM #CNPJ)
ORDER BY 
	PR.NOME_CPF1,
	PR.NOME_EMPRESA1,
	NOME_CPF2,
	PA.NOME_EMPRESA2
