SELECT
  [TIPO DE PESSOA]
  ,[CPF OU CNPJ DO SANCIONADO]
  ,[NOME INFORMADO PELO ÓRGÃO SANCIONADOR]
FROM
  [IRIS_EMPENHO].[dbo].[resultadoTipologia_ceisPessoaJuridicaMunicipios]
  JOIN #CNPJ_RAIZ AS C ON [CPF OU CNPJ DO SANCIONADO] like CONCAT(C.CNPJ,'%')
