load_connection_sql <- function(){
  library(odbc)
  library(DBI)
  library(data.table)
  library(dplyr)
  library(stringr)
  
  con <- dbConnect(odbc(),
                   Driver = "SQL Server",
                   Server = "TCERJVM48",
                   Trusted_Connection = "True",
                   database ="DGI_CONSULTA" )
  
  
  DBI::dbBegin(con)
  
  ### criando a tabela tempor?ria #CNPJ_RAIZ
  dbExecute(con, "CREATE TABLE #CNPJ_RAIZ (CNPJ VARCHAR(20))", immediate = TRUE)
  
  dbExecute(con, "INSERT INTO #CNPJ_RAIZ VALUES ('09060537'),
                              ('02812740'),
                              ('25195543'),
                              ('07028841'),
                              ('05769219')")
  
  ### criando a tabela tempor?ria #CNPJ
  dbExecute(con,"CREATE TABLE #CNPJ (CNPJ VARCHAR(20))",immediate = TRUE)
  
  dbExecute(con,"INSERT INTO #CNPJ SELECT NUM_CNPJ
               FROM DGI_CONSULTA.IMPORTADO.CNPJ
               WHERE NUM_CNPJ_RAIZ IN (SELECT CNPJ FROM #CNPJ_RAIZ)")
  
  
  ###  1 - CNPJ - (CADASTRO NACIONAL DE PESSOA JURIDICA) / CNPJ - RELACAO DE MATRIZ E FILIAL
  #Armazenando a consulta sql
  
  cnpj_sql<- paste0("SELECT 'PJ' AS CONSULTA,
				A.NUM_CNPJ,
				A.NOME,
				CASE
							WHEN A.IND_MATRIZ_FILIAL = 1 THEN 'Matriz' ELSE 'Filial'
        END AS IND_MATRIZ_FILIAL,
				A.DATA_ABERTURA_ESTABELECIMENTO, 
				A.situacao_descricao SITUACAO_CADASTRAL,
				A.DATA_SITUACAO_CADASTRAL,
				C.DESCR AS ATIVIDADE_ECONOMICA,
				D.DESCR AS NATUREZA_JURIDICA,
				E.DESCR AS PORTE_EMPRESA,
				A.DESCR_EMAIL,
				A.TIPO_LOGRADOURO,
				A.DESCR_LOGRADOURO,
				A.NUM_LOGRADOURO,
				A.DESCR_COMPLEMENTO_LOGRADOURO,
				A.NOME_BAIRRO,
				A.NUM_CEP,
				A.NOME_MUNICIPIO,
				A.SIGLA_UF,
				A.NUM_DDD1,
				A.NUM_TELEFONE1,
				A.NUM_DDD2,
				A.NUM_TELEFONE2,
				A.NUM_DDD_FAX,
				A.NUM_FAX,
				A.VALOR_CAPITAL_SOCIAL

FROM DGI_CONSULTA.IMPORTADO.CNPJ A INNER JOIN IMPORTADO.ATIVIDADE_ECONOMICA C
                ON A.COD_ATIVIDADE_ECON_PRINCIPAL = C.COD
                               INNER JOIN IMPORTADO.NATUREZA_JURIDICA D
                ON A.COD_NATUREZA_JURIDICA = D.COD
                               INNER JOIN IMPORTADO.PORTE_EMPRESA E
                ON A.COD_PORTE_EMPRESA = E.COD
WHERE A.NUM_CNPJ IN (SELECT CNPJ FROM #CNPJ)
ORDER BY A.NUM_CNPJ,
                A.IND_MATRIZ_FILIAL,
                DATA_ABERTURA_ESTABELECIMENTO")
  
  ### 2 - CNPJ - TELEFONES
  
  #Armazenando a consulta sql
  telefones_sql<-paste0("
SELECT 'TELEFONE' AS CONSULTA,
                CONCAT(A.NUM_DDD1, A.NUM_TELEFONE1) AS TELEFONE,
                A.NUM_CNPJ,
                A.NOME

FROM DGI_CONSULTA.IMPORTADO.CNPJ A
WHERE A.NUM_CNPJ IN (SELECT CNPJ FROM #CNPJ) AND NOT A.NUM_TELEFONE1 IS NULL

UNION

SELECT 'TELEFONE' AS CONSULTA,
                CONCAT(A.NUM_DDD2, A.NUM_TELEFONE2) AS TELEFONE,
                A.NUM_CNPJ,
                A.NOME
FROM DGI_CONSULTA.IMPORTADO.CNPJ A
WHERE A.NUM_CNPJ IN (SELECT CNPJ FROM #CNPJ) AND NOT A.NUM_TELEFONE2 IS NULL

UNION

SELECT 'TELEFONE' AS CONSULTA,
                CONCAT(A.NUM_DDD_FAX, A.NUM_FAX) AS TELEFONE,
                A.NUM_CNPJ,
                A.NOME

FROM DGI_CONSULTA.IMPORTADO.CNPJ A
WHERE A.NUM_CNPJ IN (SELECT CNPJ FROM #CNPJ) AND NOT A.NUM_FAX IS NULL

ORDER BY TELEFONE,
                A.NUM_CNPJ")
  
  ###  3 - CNPJ - SOCIO(S), REPRESENTANTE(S) E PARTICIPACOES SOCIETARIAS
  
  
  #Armazenando a consulta sql
  socio_sql<- paste0("
SELECT 'SOCIO' AS CONSULTA,
                A.NUM_CNPJ_EMPRESA,
                A.NOME AS NOME_SOCIO,
                A.NUM_CPF,
                B.NOME AS NOME_EMPRESA,
                C.DESCR AS QUALIFICACAO_SOCIO,
                A.DATA_ENTRADA_SOCIEDADE,
                A.DATA_DE_EXCLUSAO_NA_SOCIEDADE,
                A.VALOR_PERCENTUA_CAPITAL_SOCIAL

FROM DGI_CONSULTA.IMPORTADO.SOCIO A INNER JOIN DGI_CONSULTA.IMPORTADO.CNPJ B
                ON A.NUM_CNPJ_EMPRESA = B.NUM_CNPJ INNER JOIN DGI_CONSULTA.IMPORTADO.QUALIFICACAO_SOCIO_RESP_REPRES C
                ON A.COD_QUALIFICACAO_SOCIO = C.COD
WHERE A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ)

ORDER BY A.NUM_CPF,
                A.NOME")
  
  ### 8 - CPF - RELACAO PARENTESCO
  
  parentesco_sql<- paste0("
SELECT DISTINCT 'PARENTESCO' AS CONSULTA,
                A.CPF1,
                B.NOME AS NOME1,
                A.RELACAO,
                D.NOME AS NOME2,
                A.CPF2

FROM DGI_CONSULTA.IMPORTADO.RELACAO_PF_PF A LEFT JOIN DGI_CONSULTA.IMPORTADO.CPF B
                ON A.CPF1 = B.NUM_CPF LEFT JOIN DGI_CONSULTA.IMPORTADO.RELACAO_PF_PF C
                ON A.CPF1 = C.CPF1 INNER JOIN DGI_CONSULTA.IMPORTADO.CPF D
                ON A.CPF2 = D.NUM_CPF

WHERE A.CPF1 IN (SELECT A.NUM_CPF FROM DGI_CONSULTA.IMPORTADO.SOCIO A
                WHERE A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ))

UNION

SELECT DISTINCT 'PARENTESCO' AS CONSULTA,
                A.CPF1,
                B.NOME AS NOME1,
                A.RELACAO,
                D.NOME AS NOME2,
                A.CPF2

FROM DGI_CONSULTA.IMPORTADO.RELACAO_PF_PF A LEFT JOIN DGI_CONSULTA.IMPORTADO.CPF B
                ON A.CPF1 = B.NUM_CPF LEFT JOIN DGI_CONSULTA.IMPORTADO.RELACAO_PF_PF C
                ON A.CPF1 = C.CPF1 INNER JOIN DGI_CONSULTA.IMPORTADO.CPF D
                ON A.CPF2 = D.NUM_CPF

WHERE A.CPF2 IN (SELECT A.NUM_CPF FROM DGI_CONSULTA.IMPORTADO.SOCIO A
                WHERE A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ))

UNION

SELECT DISTINCT 'PARENTESCO' AS CONSULTA,
                A.CPF1,
                B.NOME AS NOME1,
                A.RELACAO,
                D.NOME AS NOME2,
                A.CPF2

FROM DGI_CONSULTA.IMPORTADO.PARENTESCO_RELACAO_PF_PF A LEFT JOIN DGI_CONSULTA.IMPORTADO.CPF B
                ON A.CPF1 = B.NUM_CPF LEFT JOIN DGI_CONSULTA.IMPORTADO.PARENTESCO_RELACAO_PF_PF C
                ON A.CPF1 = C.CPF1 INNER JOIN DGI_CONSULTA.IMPORTADO.CPF D
                ON A.CPF2 = D.NUM_CPF

WHERE A.CPF1 IN (SELECT A.NUM_CPF FROM DGI_CONSULTA.IMPORTADO.SOCIO A
                WHERE A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ))

UNION

SELECT DISTINCT 'PARENTESCO' AS CONSULTA,
                A.CPF1,
                B.NOME AS NOME1,
                A.RELACAO,
                D.NOME AS NOME2,
                A.CPF2

FROM DGI_CONSULTA.IMPORTADO.PARENTESCO_RELACAO_PF_PF A LEFT JOIN DGI_CONSULTA.IMPORTADO.CPF B
                ON A.CPF1 = B.NUM_CPF LEFT JOIN DGI_CONSULTA.IMPORTADO.PARENTESCO_RELACAO_PF_PF C
                ON A.CPF1 = C.CPF1 INNER JOIN DGI_CONSULTA.IMPORTADO.CPF D
                ON A.CPF2 = D.NUM_CPF

WHERE A.CPF2 IN (SELECT A.NUM_CPF FROM DGI_CONSULTA.IMPORTADO.SOCIO A
                WHERE A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ))

ORDER BY A.CPF1,
                A.CPF2")
  
  ## 17 - CPF - FUNCIONÁRIOS EMPREGADOS NA ADMINISTRAÇÃO PÚBLICA 
  
  #passagem da consulta 
  funcionariosNaAdmPublica_sql <- paste0("
SELECT DISTINCT 'FUNCIONÁRIO ORG PUB' AS CONSULTA,
  A.CO_CPF,
  B.NOME AS EMPREGADO,
  A.CO_CNPJ_CEI,
  C.NOME AS EMPREGADOR,
  C.NOME_MUNICIPIO,
  C.SIGLA_UF,
  D.DS_TIPO_VINCULO AS TIPO,
  A.DA_ADMISSAO_RAIS_DMA,
  A.DA_DESLIGAMENTO_RAIS_DM
FROM importado.EMPREGADOs A INNER JOIN importado.CPF B
  ON A.CO_CPF = B.NUM_CPF INNER JOIN importado.CNPJ C
  ON A.CO_CNPJ_CEI = C.NUM_CNPJ INNER JOIN importado.CD_TIPO_VINCULO D 
  ON A.CO_TIPO_VINCULO_RAIS = D.CD_TIPO_VINCULO
WHERE C.COD_NATUREZA_JURIDICA IN (1090, 1996, 2020, 1287, 1295, 1309, 1317, 1325, 1333, 1341, 1015,
  1023, 1031, 1040, 1058, 1066, 1074, 1082, 1104, 1112, 1120, 1139, 1147, 1155, 1163, 1171, 1180,
  1201, 1210, 1236, 1244, 1252, 1260, 1279, 2011, 2038) AND
  CO_CPF IN (SELECT A.CO_CPF
    FROM importado.EMPREGADOs A INNER JOIN importado.CD_CBO_OCUPACAO B
      ON A.CO_CBO_RAIS = B.CD_CBO_OCUPACAO LEFT JOIN importado.CNPJ C
      ON A.CO_CNPJ_CEI = C.NUM_CNPJ
    WHERE A.CO_CNPJ_CEI IN (SELECT CNPJ FROM #CNPJ) AND B.TIPO = 'Ocupação'
    UNION
    SELECT B.NUM_CPF
    FROM importado.CAGED A INNER JOIN importado.CPF B
      ON A.CPF = B.NUM_CPF INNER JOIN importado.CNPJ C
      ON A.CNPJ = C.NUM_CNPJ LEFT JOIN importado.CD_CBO_OCUPACAO D
      ON A.CBO_2002_OCUPACAO = D.CD_CBO_OCUPACAO
    WHERE A.CNPJ IN (SELECT A.NUM_CNPJ_EMPRESA
      FROM importado.SOCIO A  
      WHERE A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ)))
")
  
  dbExecute(con,"WITH
QRY_SOCIO AS (SELECT 'SOCIO' AS CONSULTA,
  A.NUM_CNPJ_EMPRESA,
  B.NOME AS NOME_EMPRESA,
  A.NUM_CPF AS CPF_SOCIO,
  A.NOME AS NOME_SOCIO,
  C.DESCR AS QUALIFICACAO_SOCIO,
  A.DATA_ENTRADA_SOCIEDADE,
  A.DATA_DE_EXCLUSAO_NA_SOCIEDADE,
  A.VALOR_PERCENTUA_CAPITAL_SOCIAL
FROM importado.SOCIO A INNER JOIN importado.CNPJ B
  ON A.NUM_CNPJ_EMPRESA = B.NUM_CNPJ INNER JOIN importado.QUALIFICACAO_SOCIO_RESP_REPRES C
  ON A.COD_QUALIFICACAO_SOCIO = C.COD
WHERE A.NUM_CNPJ_EMPRESA IN (SELECT CNPJ FROM #CNPJ))

SELECT * INTO #TEMP_SOCIO
FROM QRY_SOCIO", immediate = TRUE)
  
  
  dbExecute(con,"SELECT DISTINCT * INTO #TEMP_CPF_SOCIO
FROM (SELECT CPF_SOCIO AS CPF
FROM #TEMP_SOCIO) AS TEMP_CPF_SOCIO

SELECT * FROM #TEMP_SOCIO
ORDER BY CPF_SOCIO
", immediate = TRUE)
  
  # 18 - CPF - S?CIOS EMPREGADOS NA ADMINISTRA??O P?BLICA
  
  #passagem da consulta
  
  cpfSociosNaAdmPublica_sql <- paste0("
SELECT DISTINCT 'SOCIO ORG PUB' AS CONSULTA,
	A.CO_CPF,
	B.NOME AS EMPREGADO,
	A.CO_CNPJ_CEI,
	C.NOME AS EMPREGADOR,
	C.NOME_MUNICIPIO,
	C.SIGLA_UF,
	D.DS_TIPO_VINCULO AS TIPO,
	A.DA_ADMISSAO_RAIS_DMA,
	A.DA_DESLIGAMENTO_RAIS_DM
FROM importado.EMPREGADOS A INNER JOIN importado.CPF B
	ON A.CO_CPF = B.NUM_CPF INNER JOIN importado.CNPJ C
	ON A.CO_CNPJ_CEI = C.NUM_CNPJ INNER JOIN importado.CD_TIPO_VINCULO D
	ON A.CO_TIPO_VINCULO_RAIS = D.CD_TIPO_VINCULO
WHERE C.COD_NATUREZA_JURIDICA IN (1090, 1996, 2020, 1287, 1295, 1309, 1317, 1325, 1333, 1341, 1015,
	1023, 1031, 1040, 1058, 1066, 1074, 1082, 1104, 1112, 1120, 1139, 1147, 1155, 1163, 1171, 1180,
	1201, 1210, 1236, 1244, 1252, 1260, 1279, 2011, 2038) AND

	CO_CPF IN (SELECT CPF FROM #TEMP_CPF_SOCIO)    
ORDER BY A.CO_CPF,
	A.CO_CNPJ_CEI,
	A.DA_ADMISSAO_RAIS_DMA,
	A.DA_DESLIGAMENTO_RAIS_DM")
  
  # executando a consulta
  cnpj<- dbGetQuery(con, cnpj_sql)
  telefones <- dbGetQuery(con, telefones_sql)
  socios <- dbGetQuery(con, socio_sql)
  parentesco <- dbGetQuery(con, parentesco_sql)
  func_na_adm_publica <- dbGetQuery(con, funcionariosNaAdmPublica_sql)
  socio_org_publico <- dbGetQuery(con, cpfSociosNaAdmPublica_sql)
  
  # fecha a conex?o
  DBI::dbDisconnect(con)
  
  list(cnpj = cnpj, telefones = telefones, socios = socios, parentesco = parentesco,
       func_na_adm_publica = func_na_adm_publica, socio_org_publico = socio_org_publico)
  
}